### ISSUE TITLE
bug: Failing to evaluate 'false'

### ISSUE THREAD

**Issue by Woynert** [fridasor/tabscraper#1]
Log:
```
$ python tabber.py el cuarteto de nos                                         
Traceback (most recent call last):
el%20cuarteto%20de%20nos
  File "tabber.py", line 256, in <module>
    d = dict_from_search(srch)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "tabber.py", line 143, in dict_from_search
    d = create_dict(tabs)
        ^^^^^^^^^^^^^^^^^
  File "tabber.py", line 90, in create_dict
    tab_d = eval(tabstring_i)
            ^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'false' is not defined. Did you mean: 'False'?
```

It seems this only happens with some specific prompts, for instance: `el cuarteto de nos` gives an error, but `el cuarteto de nos yo` works fine.

As a quick fix replace line 90 from:
```
tab_d = eval(tabstring_i)
```
to:
```
tab_d = eval(tabstring_i.replace("false", "False"))
```

**Comment by fridasor** [comment]
Thank you kindly, it is fixed now.
